using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;

namespace LothbrokAI.Quests
{
    /// <summary>
    /// LetterSystem tracks physical Roleplay items generated by the AI or Spymasters.
    /// Since dynamically creating new item definitions in Bannerlord at runtime is unsafe
    /// without patching XML, this system tracks RP items as data associated with the 
    /// vanilla "jewelry" or "book" item categories if physical representation is needed.
    /// </summary>
    public static class LetterSystem
    {
        // Tracks generated RP items. Key: ItemName, Value: ItemDescription
        public static Dictionary<string, string> PlayerRPItems = new Dictionary<string, string>();

        /// <summary>
        /// Creates an RP item. Currently entirely abstract (data-driven)
        /// rather than creating a physical item in the Bannerlord inventory
        /// to prevent XML corruption on saves.
        /// </summary>
        public static void CreateRPItem(string itemName, string content)
        {
            if (string.IsNullOrEmpty(itemName)) return;

            PlayerRPItems[itemName] = content;
            LothbrokSubModule.Log($"RP Item Created: {itemName}", TaleWorlds.Library.Debug.DebugColor.Green);
            
            TaleWorlds.Library.InformationManager.DisplayMessage(new TaleWorlds.Library.InformationMessage($"Received RP Item: {itemName}", TaleWorlds.Library.Color.FromUint(0x00FF00FF)));
        }

        public static string GetInventoryRPContext()
        {
            if (PlayerRPItems.Count == 0) return null;

            var sb = new System.Text.StringBuilder();
            sb.AppendLine("The Player is holding the following Roleplay Items:");
            foreach (var kvp in PlayerRPItems)
            {
                // In a heavy implementation we'd provide the full text of the letter
                sb.AppendLine($"- {kvp.Key}");
            }
            return sb.ToString();
        }
    }
}
